name: Build and Upload Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Step 3: Run the build
      - name: Build binaries
        run: make build_all

      # Step 4: Upload the artifacts
      - name: Upload binaries and checksums
        uses: actions/upload-artifact@v3
        with:
          name: binaries-and-checksums
          path: bin/*
